runtime: python27
api_version: 1
threadsafe: true
service: default

handlers:
- url: /.*
  script: main.app

- url: /resources
  static_dir: resources

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: "2.5.2"
